<a href="https://colab.research.google.com/github/Syntaxjelly/Assignment-from-Class-4/blob/main/Copy_of_Assignment_from_Class_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#install required package
!pip install numpy pandas matplotlib
#import libraised
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.0.2
Pandas version: 2.2.2


In [ ]:
#creating numpy arrey
arrey1=np.array([1,2,3,4,5,6])
arrey2=np.array([[1,2,4],[3,4,5]])

print("1D array:",arrey1)
print('2D array:',arrey2)
print('array shape:',arrey1.shape)
print('array dtype:',arrey1.dtype)

1D array: [1 2 3 4 5 6]
2D array: [[1 2 4]
 [3 4 5]]
array shape: (6,)
array dtype: int64


In [ ]:
#different types of numpy arrey
zeros_array =np.zeros((3,10),dtype=int)
ones_array=np.ones((2,4),dtype=int)
range_array=np.arange(0,10,2)
linspace_array=np.linspace(0,1,5)

print("Zeros array: \n",zeros_array)
print("ones_array \n:",ones_array)
print("range_array :\n",range_array)

Zeros array: 
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
ones_array 
: [[1 1 1 1]
 [1 1 1 1]]
range_array :
 [0 2 4 6 8]


In [ ]:
#mathemetical opperation on array
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 3, 4, 5, 6])
c=np.array([4,5,6,5,6])
# Element-wise operations
print("Addition:",a+b+c)
print("Multiplycation:",(a*b)*c)
print("power:",b**3)
print("Squire root:",np.sqrt(c))

# Statistical operations
print("Mean:",np.mean(a))
print("standart deviation:",np.std(a))
print("min:",np.min(a))
print("max:",np.max(c))

#Broadcasting array
matrix=np.array([[1,2,3],[4,5,6]])
vector=np.array([10,20,30])
result=matrix+vector
print("Broadcasting array: \n",result)

Addition: [ 7 10 13 14 17]
Multiplycation: [  8  30  72 100 180]
power: [  8  27  64 125 216]
Squire root: [2.         2.23606798 2.44948974 2.23606798 2.44948974]
Mean: 3.0
standart deviation: 1.4142135623730951
min: 1
max: 6
Broadcasting array: 
 [[11 22 33]
 [14 25 36]]


In [ ]:
arr= np.array([10,20,30,40,50])
print("Element on indx 2:",arr[2])
print("slicing array(1 to 3): \n",arr[1:4])
arr_2D=np.array([[1,2,3,4],[4,5,6,7],[4,5,8,9]])
print("slicing 2d array: \n",arr_2D[:2])

Element on indx 2: 30
slicing array(1 to 3): 
 [20 30 40]
slicing 2d array: 
 [[1 2 3 4]
 [4 5 6 7]]


In [ ]:
#pandas for creating dataframes
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [24, 27, 22],
        'City': ['New York', 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
       Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago


In [ ]:
#basic dataframe information
print("\n Dataframe Info: ")
print(df.info())
print("\n Data Description:")
print(df.describe())


 Dataframe Info: 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None

 Data Description:
             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000


In [ ]:
# Accessing a single column
print("Names column:\n", df['Name'])
# Accessing a single column
print("city column:\n", df['City'])
# Accessing multiple columns

print("\nName and Age columns:\n", df[['Name', 'Age']])


Names column:
 0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
city column:
 0       New York
1    Los Angeles
2        Chicago
Name: City, dtype: object

Name and Age columns:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22


In [ ]:
# Convert NumPy array to DataFrame
np_array=np.array([1,2,4,5])
dataframe_fromarray = pd.DataFrame(np_array)
print("\n dataframe_fromarray:")

print(dataframe_fromarray)


 dataframe_fromarray:
   0
0  1
1  2
2  4
3  5


In [3]:
from google.colab import drive
import warnings
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
file_location='/content/drive/MyDrive/Research Dataset/diabetes.csv'
df=pd.read_csv(file_location)
print("Dataset load succes.shape:",df.shape)

Dataset load succes.shape: (768, 9)


In [21]:
#for quick array
print(df.head())
print(df.tail())
print(" \ndataset info:\n ")
print(df.info())

#statictis
print("\n descriptive statictis:")
print(df.describe())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766    

In [22]:
#if we want to find missig value
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


# ***Excercise for numpy ***

In [8]:
# Import necessary library
import numpy as np

# Create a NumPy array with 20 random integers between 1 and 100
random_array=np.random.randint(1,101,20)

# Display the NumPy array
print("Random number: \n",random_array)
# 1. Find the sum of all elements
total_sum=np.sum(random_array)
print("total sum:",total_sum)


# 2. Find the maximum and minimum values in the array
max_value = np.max(random_array)
print("Maximumu value of array:",max_value)
min_value=np.min(random_array)
print("Minimum value of array:",min_value)


Random number: 
 [28 37 41 59 68 22 70  6 37 94 11 85 97 19 97 72 13 57 74 62]
total sum: 1049
Maximumu value of array: 97
Minimum value of array: 6


# *Excercise for pandas *

In [30]:
# Import necessary libraries
import pandas as pd
import numpy as np

# 1. Create a DataFrame with 5 rows and 3 columns of random numbers
random_matrix=np.random.randint(1,101,size=(5,3))
df=pd.DataFrame(random_matrix,columns=['A', 'B', 'C'])

# The DataFrame is generated from a 5x3 matrix of random integers between 1 and 100.


df=pd.DataFrame(random_matrix,columns=['A', 'B', 'C'])
# Display the DataFrame

print("Generated Dataframe:\n",df)
# 2. Compute the sum of each column
total_sum=df.sum()

# The .sum() function computes the sum for each column in the DataFrame.

print(total_sum)
# 3. Compute the mean of each column
mean_matrix=df.mean()
# The .mean() function computes the mean (average) of each column in the DataFrame.
print(mean_matrix)

Generated Dataframe:
     A   B   C
0  74  89  35
1  84  73   5
2  77  41  86
3  62   8  94
4  76  20  47
A    373
B    231
C    267
dtype: int64
A    74.6
B    46.2
C    53.4
dtype: float64
